services:
  db:
    image: mysql
    restart: always
    volumes:
      - ../db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=demo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=db
       - PMA_USER=root
       - PMA_PASSWORD=${DB_ROOT_PASSWORD} 
