services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: "demo"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
