services:
  db:
    image: mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}

  app:
    build: .
    ports:
      - ${APP_PORT}:9000
    restart: always
    environment:
      - DB_PORT=${DB_PORT}
      - PMA_PORT=${PMA_PORT}
      - APP_PORT=${APP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST_NAME_DEV=${DB_HOST_NAME_DEV}
      - DB_HOST_NAME_PRODUCTION=${DB_HOST_NAME_PRODUCTION}
      - MODE=production
